# Generated by Django 4.2.5 on 2025-03-14 05:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('empty', 'Empty'), ('admin', 'Admin'), ('manager_a', 'Manager_a'), ('manager_b', 'Manager_b'), ('kepper_a', 'Kepper_a'), ('kepper_b', 'Kepper_b'), ('provider', 'Provider')], default='empty', max_length=20)),
                ('image', models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='user_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('full', 'Full'), ('espece', 'Kind')], default='full', max_length=10)),
                ('type_disch', models.CharField(choices=[('slip', 'Slip'), ('cert', 'Cert')], default='slip', max_length=10)),
                ('discharged', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='Decharges/%Y/')),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='user_images/default.jpg', upload_to='Articles/%Y/')),
                ('price', models.IntegerField(default=0)),
                ('rate_per_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unite', models.CharField(choices=[('bag', 'Bag'), ('can', 'Can'), ('cardboard', 'Cardboard')], default='bag', max_length=20)),
                ('divider', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalOperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('function_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('default', 'Default'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='default', max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='menu_images/')),
                ('type_menu', models.CharField(choices=[('food', 'Food'), ('other', 'Other')], default='food', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('speciale', 'Speciale'), ('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], default='speciale', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='user_images/default.jpg', upload_to='Unit/%Y/')),
                ('short_name', models.CharField(default='NULL', max_length=50, unique=True)),
                ('recipient', models.CharField(default='NULL', max_length=200)),
                ('g_staff', models.CharField(choices=[('emat', 'Emat'), ('emaa', 'Emaa'), ('emam', 'Emam'), ('hcgn', 'Hcgn')], default='emat', max_length=20)),
                ('area', models.CharField(choices=[('speciale', 'Speciale'), ('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], default='speciale', max_length=100)),
                ('type_of_unit', models.CharField(choices=[('current', 'Current'), ('mission', 'Mission'), ('single', 'Single')], default='current', max_length=20)),
                ('category', models.CharField(choices=[('unit', 'Unit'), ('school', 'School'), ('service', 'Service')], default='unit', max_length=20)),
                ('is_created', models.BooleanField(default=False)),
                ('effective', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='menu_images/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spens_disch', to='app.discharge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='app.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='itemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('store_type', models.CharField(choices=[('store_a', 'Store_a'), ('store_b', 'Store_b')], default='store_a', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.item')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DischargedLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0)),
                ('forfait', models.BooleanField(default=False)),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_line', to='app.discharge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_line_disch', to='app.item')),
            ],
        ),
        migrations.AddField(
            model_name='discharge',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislines_units', to='app.unit'),
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('nomber_of_days', models.IntegerField(default=0)),
                ('discharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_archiv', to='app.discharge')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_archiv', to='app.order')),
            ],
        ),
    ]
