# Generated by Django 4.2.5 on 2024-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('empty', 'Empty'), ('admin', 'Admin'), ('manager_a', 'Manager_a'), ('manager_b', 'Manager_b'), ('kepper_a', 'Kepper_a'), ('kepper_b', 'Kepper_b'), ('provider', 'Provider')], default='empty', max_length=20),
        ),
    ]
