# Generated by Django 4.2.5 on 2024-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_item_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLine',
        ),
    ]
