# Generated by Django 4.2.5 on 2023-12-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_unit_chief_alter_unit_effective"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="rate_per_person",
            new_name="rate_per_days",
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(null=True, upload_to="Articles/%Y/"),
        ),
    ]
