# Generated by Django 4.2.5 on 2025-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_ref_otherspend_ref_spend_ref_subarea_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherspend',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
