# Generated by Django 4.2.5 on 2024-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_offset_user_address_alter_itemstock_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
