# Generated by Django 4.2.5 on 2025-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_otherspend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherspend',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spend',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
