# Generated by Django 4.2.5 on 2025-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_otherspend_amount_alter_spend_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherspend',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='spend',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
