# Generated by Django 4.2.5 on 2024-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='uploads/user_images/'),
        ),
    ]
