# Generated by Django 4.2.5 on 2024-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='uploads/user_images/default.jpg', null=True, upload_to='uploads/user_images/'),
        ),
    ]
