# Generated by Django 4.2.5 on 2024-06-13 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
