# Generated by Django 4.2.5 on 2024-06-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
