# Generated by Django 4.2.5 on 2024-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_archives_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
