# Generated by Django 4.2.5 on 2024-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_area_ref_alter_discharge_ref_alter_item_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signateure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('function_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='first', max_length=20)),
            ],
        ),
    ]
