# Generated by Django 4.2.5 on 2024-07-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_signateure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signateure',
            new_name='SignalOperators',
        ),
    ]
