# Generated by Django 4.2.5 on 2024-12-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_signateure_signaloperators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaloperators',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=20),
        ),
    ]
