# Generated by Django 4.2.5 on 2024-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_signaloperators_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaloperators',
            name='position',
            field=models.CharField(choices=[('default', 'Default'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='default', max_length=20),
        ),
    ]
