# Generated by Django 4.2.5 on 2024-12-07 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_signaloperators_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaloperators',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaloperators',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signaloperators',
            name='ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
