# Generated by Django 4.2.5 on 2024-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_signaloperators_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaloperators',
            name='position',
            field=models.CharField(choices=[('default', 'Default'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='default', max_length=20, unique=True),
        ),
    ]
