# Generated by Django 4.2.5 on 2024-12-27 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_signaloperators_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaloperators',
            name='grade',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
