# Generated by Django 4.2.5 on 2025-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_signaloperators_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type_of_unit',
            field=models.CharField(choices=[('mission', 'Mission'), ('service', 'Service'), ('single', 'Single')], default='unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('unit', 'Unit'), ('school', 'School')], default='unit', max_length=20),
        ),
    ]
