# Generated by Django 4.2.5 on 2025-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_unit_type_of_unit_alter_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='g_staff',
            field=models.CharField(choices=[('emat', 'Emat'), ('emaa', 'Emaa'), ('emam', 'Emam'), ('hcgn', 'Hcgn')], default='emat', max_length=20),
        ),
    ]
