# Generated by Django 4.2.5 on 2025-01-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_unit_g_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddField(
            model_name='subarea',
            name='unites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area_unit', to='app.unit'),
        ),
    ]
