# Generated by Django 4.2.5 on 2025-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_subarea_remove_unit_area_delete_area_subarea_unites'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.CharField(choices=[('speciale', 'Speciale'), ('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], default='speciale', max_length=100),
        ),
    ]
